### ISSUE TITLE
docker-compose up 

### ISSUE THREAD

**Issue by Sam-Jain** [ParrotPrediction/docker-course-xgboost#2]
While trying to run the '$ docker-compose up' command got this error:
In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.

**Comment by khozzy** [comment]
Hi, which version of Docker and Docker Compose are you using?

**Comment by Sam-Jain** [comment]
I am currently using the following:

Docker version 1.12.5, build 7392c3b
and docker-compose version 1.5.2, build unknown



________________________________

**Comment by khozzy** [comment]
Please update your docker-compose to at least 1.7.*
